/*
 DMXzone Nivo Slider
 Version: 3.0.0
 (c) 2014 DMXzone.com
 @build 21-10-2014 13:21:05
*/
(function(b){var x={};b.fn.dmxNivoSlider=function(p){if("string"===typeof p){var t=this.find(".nivoSlider").data("nivoslider");args=Array.prototype.slice.call(arguments,1);t&&t[p]&&t[p].apply(t,args);return this}var d=b.extend({},x,p),s=this,a=this[0].id,f=b.dmxDataBindings;d.beforeChange=function(){var b=this.getSlider().find("img:eq("+this.getCurrentSlide()+")");b.parent().is("a")&&b.parent().trigger("blur")};d.afterChange=function(){var b=this.getSlider().find("img:eq("+this.getCurrentSlide()+
")");b.parent().is("a")&&b.parent().trigger("focus")};d.controlNavThumbs&&(d.controlNav=!0);f&&d.repeatElement?f.globalScope.watch(d.repeatElement,function(k){var q=s.find(".nivoSlider").data("nivoslider");q&&q.destroy();s.empty();if(k&&k.length){var p=b('<div class="nivoSlider"></div>').appendTo(s),m=0;b.each(k,function(k,q){var g={},r=new f.Scope;r.set(q);for(var n in d.dynSlides)d.dynSlides[n]&&(g[n]=f.$parseTemplate(d.dynSlides[n],r));g.url&&(r=b('<img src="'+g.url+'">'),g.width&&r.attr("width",
g.width),g.height&&r.attr("height",g.height),g.thumb&&r.attr("data-thumb",g.thumb),g.transition&&r.attr("data-transition",g.transition),g.title&&(g.description?(n=a+"_"+ ++m,p.after('<div id="'+n+'" class="nivo-html-caption"><h4>'+g.title+"</h4><p>"+g.description+"</p></div>"),r.attr("title","#"+n)):r.attr("title",g.title)),p.append(r),g.link||g.onclick||g.onblur||g.onfocus||g.onmouseover||g.onmouseout)&&(n=b('<a href="'+(g.link||"javascript:void();")+'">'),g.target&&n.attr("target",g.target),g.onclick&&
n.attr("onclick",g.onclick),g.onblur&&n.attr("onblur",g.onblur),g.onfocus&&n.attr("onfocus",g.onfocus),g.onmouseover&&n.attr("onmouseover",g.onmouseover),g.onmouseout&&n.attr("onmouseout",g.onmouseout),r.wrap(n))});p.nivoSlider(d)}}):s.find(".nivoSlider").nivoSlider(d)}})(jQuery);
(function(b){var x=function(p,t){var d=b.extend({},b.fn.nivoSlider.defaults,t),s=this,a={currentSlide:0,currentImage:"",totalSlides:0,running:!1,paused:!1,stop:!1,controlNavEl:!1},f=b(p);f.data("nivo:vars",a).addClass("nivoSlider");var k=f.children();k.each(function(){var c=b(this),w="";c.is("img")||(c.is("a")&&(c.addClass("nivo-imageLink"),w=c),c=c.find("img:first"));var e=0===e?c.attr("width"):c.width(),d=0===d?c.attr("height"):c.height();""!==w&&w.css("display","none");c.css("display","none");
a.totalSlides++});d.randomStart&&(d.startSlide=Math.floor(Math.random()*a.totalSlides));0<d.startSlide&&(d.startSlide>=a.totalSlides&&(d.startSlide=a.totalSlides-1),a.currentSlide=d.startSlide);b(k[a.currentSlide]).is("img")?a.currentImage=b(k[a.currentSlide]):a.currentImage=b(k[a.currentSlide]).find("img:first");b(k[a.currentSlide]).is("a")&&b(k[a.currentSlide]).css("display","block");var q=b("<img/>").addClass("nivo-main-image");q.attr("src",a.currentImage.attr("src")).show();f.append(q);b(window).resize(function(){f.children("img").width(f.width());
q.attr("src",a.currentImage.attr("src"));q.stop().height("auto");b(".nivo-slice").remove();b(".nivo-box").remove()});f.append(b('<div class="nivo-caption"></div>'));var x=function(c){var w=b(".nivo-caption",f);if(""!=a.currentImage.attr("title")&&void 0!=a.currentImage.attr("title")){var e=a.currentImage.attr("title");"#"==e.substr(0,1)&&(e=b(e).html());"block"==w.css("display")?setTimeout(function(){w.html(e)},c.animSpeed):(w.html(e),w.stop().fadeIn(c.animSpeed))}else w.stop().fadeOut(c.animSpeed)};
x(d);var m=0;!d.manualAdvance&&1<k.length&&(m=setInterval(function(){n(f,k,d,!1)},d.pauseTime));d.directionNav&&(f.append('<div class="nivo-directionNav"><a class="nivo-prevNav">'+d.prevText+'</a><a class="nivo-nextNav">'+d.nextText+"</a></div>"),b(f).on("click","a.nivo-prevNav",function(){if(a.running)return!1;clearInterval(m);m="";a.currentSlide-=2;n(f,k,d,"prev")}),b(f).on("click","a.nivo-nextNav",function(){if(a.running)return!1;clearInterval(m);m="";n(f,k,d,"next")}));if(d.controlNav){a.controlNavEl=
b('<div class="nivo-controlNav"></div>');f.after(a.controlNavEl);for(var u=0;u<k.length;u++)if(d.controlNavThumbs){a.controlNavEl.addClass("nivo-thumbs-enabled");var v=k.eq(u);v.is("img")||(v=v.find("img:first"));v.attr("data-thumb")&&a.controlNavEl.append('<a class="nivo-control" rel="'+u+'"><img src="'+v.attr("data-thumb")+'" alt="" /></a>')}else a.controlNavEl.append('<a class="nivo-control" rel="'+u+'">'+(u+1)+"</a>");b("a:eq("+a.currentSlide+")",a.controlNavEl).addClass("active");b("a",a.controlNavEl).bind("click",
function(){if(a.running||b(this).hasClass("active"))return!1;clearInterval(m);m="";q.attr("src",a.currentImage.attr("src"));a.currentSlide=b(this).attr("rel")-1;n(f,k,d,"control")})}d.pauseOnHover&&f.hover(function(){a.paused=!0;clearInterval(m);m=""},function(){a.paused=!1;""!==m||d.manualAdvance||(m=setInterval(function(){n(f,k,d,!1)},d.pauseTime))});f.bind("nivo:animFinished",function(){q.attr("src",a.currentImage.attr("src"));a.running=!1;b(k).each(function(){b(this).is("a")&&b(this).css("display",
"none")});b(k[a.currentSlide]).is("a")&&b(k[a.currentSlide]).css("display","block");""!==m||a.paused||d.manualAdvance||(m=setInterval(function(){n(f,k,d,!1)},d.pauseTime));d.afterChange.call(s)});var g=function(c,a,e){b(e.currentImage).parent().is("a")&&b(e.currentImage).parent().css("display","block");b('img[src="'+e.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").width(c.width()).css("visibility","hidden").show();for(var d=b('img[src="'+e.currentImage.attr("src")+'"]',
c).not(".nivo-main-image,.nivo-control img").parent().is("a")?b('img[src="'+e.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").parent().height():b('img[src="'+e.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").height(),h=0;h<a.slices;h++){var l=Math.round(c.width()/a.slices);h===a.slices-1?c.append(b('<div class="nivo-slice" name="'+h+'"><img src="'+e.currentImage.attr("src")+'" style="position:absolute; width:'+c.width()+"px; height:auto; display:block !important; top:0; left:-"+
(l+h*l-l)+'px;" /></div>').css({left:l*h+"px",width:c.width()-l*h+"px",height:d+"px",opacity:"0",overflow:"hidden"})):c.append(b('<div class="nivo-slice" name="'+h+'"><img src="'+e.currentImage.attr("src")+'" style="position:absolute; width:'+c.width()+"px; height:auto; display:block !important; top:0; left:-"+(l+h*l-l)+'px;" /></div>').css({left:l*h+"px",width:l+"px",height:d+"px",opacity:"0",overflow:"hidden"}))}b(".nivo-slice",c).height(d);q.stop().animate({height:b(e.currentImage).height()},a.animSpeed)},
r=function(c,a,e){b(e.currentImage).parent().is("a")&&b(e.currentImage).parent().css("display","block");b('img[src="'+e.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").width(c.width()).css("visibility","hidden").show();for(var d=Math.round(c.width()/a.boxCols),h=Math.round(b('img[src="'+e.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").height()/a.boxRows),l=0;l<a.boxRows;l++)for(var g=0;g<a.boxCols;g++)g===a.boxCols-1?c.append(b('<div class="nivo-box" name="'+
g+'" rel="'+l+'"><img src="'+e.currentImage.attr("src")+'" style="position:absolute; width:'+c.width()+"px; height:auto; display:block; top:-"+h*l+"px; left:-"+d*g+'px;" /></div>').css({opacity:0,left:d*g+"px",top:h*l+"px",width:c.width()-d*g+"px"})):c.append(b('<div class="nivo-box" name="'+g+'" rel="'+l+'"><img src="'+e.currentImage.attr("src")+'" style="position:absolute; width:'+c.width()+"px; height:auto; display:block; top:-"+h*l+"px; left:-"+d*g+'px;" /></div>').css({opacity:0,left:d*g+"px",
top:h*l+"px",width:d+"px"})),b('.nivo-box[name="'+g+'"]',c).height(b('.nivo-box[name="'+g+'"] img',c).height()+"px");q.stop().animate({height:b(e.currentImage).height()},a.animSpeed)},n=function(c,a,e,d){var h=c.data("nivo:vars");h&&h.currentSlide===h.totalSlides-1&&e.lastSlide.call(s);if((!h||h.stop)&&!d)return!1;e.beforeChange.call(s);d?("prev"===d&&q.attr("src",h.currentImage.attr("src")),"next"===d&&q.attr("src",h.currentImage.attr("src"))):q.attr("src",h.currentImage.attr("src"));h.currentSlide++;
h.currentSlide===h.totalSlides&&(h.currentSlide=0,e.slideshowEnd.call(s));0>h.currentSlide&&(h.currentSlide=h.totalSlides-1);b(a[h.currentSlide]).is("img")?h.currentImage=b(a[h.currentSlide]):h.currentImage=b(a[h.currentSlide]).find("img:first");e.controlNav&&(b("a",h.controlNavEl).removeClass("active"),b("a:eq("+h.currentSlide+")",h.controlNavEl).addClass("active"));x(e);b(".nivo-slice",c).remove();b(".nivo-box",c).remove();var l=e.effect;a="";"random"===e.effect&&(a="sliceDownRight sliceDownLeft sliceUpRight sliceUpLeft sliceUpDown sliceUpDownLeft fold fade boxRandom boxRain boxRainReverse boxRainGrow boxRainGrowReverse".split(" "),
l=a[Math.floor(Math.random()*(a.length+1))],void 0===l&&(l="fade"));-1!==e.effect.indexOf(",")&&(a=e.effect.split(","),l=a[Math.floor(Math.random()*a.length)],void 0===l&&(l="fade"));h.currentImage.attr("data-transition")&&(l=h.currentImage.attr("data-transition"));h.running=!0;var f=0,k=0,m=a="",n="";a="";if("sliceDown"===l||"sliceDownRight"===l||"sliceDownLeft"===l)g(c,e,h),k=f=0,a=b(".nivo-slice",c),"sliceDownLeft"===l&&(a=b(".nivo-slice",c)._reverse()),a.each(function(){var a=b(this);a.css({top:"0px"});
k===e.slices-1?setTimeout(function(){a.animate({opacity:"1.0"},e.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+f):setTimeout(function(){a.animate({opacity:"1.0"},e.animSpeed)},100+f);f+=50;k++});else if("sliceUp"===l||"sliceUpRight"===l||"sliceUpLeft"===l)g(c,e,h),k=f=0,a=b(".nivo-slice",c),"sliceUpLeft"===l&&(a=b(".nivo-slice",c)._reverse()),a.each(function(){var a=b(this);a.css({bottom:"0px"});k===e.slices-1?setTimeout(function(){a.animate({opacity:"1.0"},e.animSpeed,"",function(){c.trigger("nivo:animFinished")})},
100+f):setTimeout(function(){a.animate({opacity:"1.0"},e.animSpeed)},100+f);f+=50;k++});else if("sliceUpDown"===l||"sliceUpDownRight"===l||"sliceUpDownLeft"===l){g(c,e,h);var p=k=f=0;a=b(".nivo-slice",c);"sliceUpDownLeft"===l&&(a=b(".nivo-slice",c)._reverse());a.each(function(){var a=b(this);0===k?(a.css("top","0px"),k++):(a.css("bottom","0px"),k=0);p===e.slices-1?setTimeout(function(){a.animate({opacity:"1.0"},e.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+f):setTimeout(function(){a.animate({opacity:"1.0"},
e.animSpeed)},100+f);f+=50;p++})}else if("fold"===l)g(c,e,h),k=f=0,b(".nivo-slice",c).each(function(){var a=b(this),d=a.width();a.css({top:"0px",width:"0px"});k===e.slices-1?setTimeout(function(){a.animate({width:d,opacity:"1.0"},e.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+f):setTimeout(function(){a.animate({width:d,opacity:"1.0"},e.animSpeed)},100+f);f+=50;k++});else if("fade"===l)g(c,e,h),m=b(".nivo-slice:first",c),m.css({width:c.width()+"px"}),m.animate({opacity:"1.0"},2*e.animSpeed,
"",function(){c.trigger("nivo:animFinished")});else if("slideInRight"===l)g(c,e,h),m=b(".nivo-slice:first",c),m.css({width:"0px",opacity:"1"}),m.animate({width:c.width()+"px"},2*e.animSpeed,"",function(){c.trigger("nivo:animFinished")});else if("slideInLeft"===l)g(c,e,h),m=b(".nivo-slice:first",c),m.css({width:"0px",opacity:"1",left:"",right:"0px"}),m.animate({width:c.width()+"px"},2*e.animSpeed,"",function(){m.css({left:"0px",right:""});c.trigger("nivo:animFinished")});else if("boxRandom"===l)r(c,
e,h),n=e.boxCols*e.boxRows,f=k=0,a=z(b(".nivo-box",c)),a.each(function(){var a=b(this);k===n-1?setTimeout(function(){a.animate({opacity:"1"},e.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+f):setTimeout(function(){a.animate({opacity:"1"},e.animSpeed)},100+f);f+=20;k++});else if("boxRain"===l||"boxRainReverse"===l||"boxRainGrow"===l||"boxRainGrowReverse"===l){r(c,e,h);var n=e.boxCols*e.boxRows,t=f=k=0,u=0,v=[];v[t]=[];a=b(".nivo-box",c);if("boxRainReverse"===l||"boxRainGrowReverse"===
l)a=b(".nivo-box",c)._reverse();a.each(function(){v[t][u]=b(this);u++;u===e.boxCols&&(t++,u=0,v[t]=[])});for(h=0;h<2*e.boxCols;h++){a=h;for(d=0;d<e.boxRows;d++)0<=a&&a<e.boxCols&&(function(a,d,f,g,h){var k=b(v[a][d]),m=k.width(),n=k.height();"boxRainGrow"!==l&&"boxRainGrowReverse"!==l||k.width(0).height(0);g===h-1?setTimeout(function(){k.animate({opacity:"1",width:m,height:n},e.animSpeed/1.3,"",function(){c.trigger("nivo:animFinished")})},100+f):setTimeout(function(){k.animate({opacity:"1",width:m,
height:n},e.animSpeed/1.3)},100+f)}(d,a,f,k,n),k++),a--;f+=100}}},z=function(a){for(var b,e,d=a.length;d;b=parseInt(Math.random()*d,10),e=a[--d],a[d]=a[b],a[b]=e);return a},y=function(a){this.console&&"undefined"!==typeof console.log&&console.log(a)};this.stop=function(){b(p).data("nivo:vars").stop||(b(p).data("nivo:vars").stop=!0,y("Stop Slider"))};this.start=function(){b(p).data("nivo:vars").stop&&(b(p).data("nivo:vars").stop=!1,y("Start Slider"))};this.prev=function(){a.running||(clearInterval(m),
m="",a.currentSlide-=2,n(f,k,d,"prev"))};this.next=function(){a.running||(clearInterval(m),m="",n(f,k,d,"next"))};this.first=function(){a.running||(clearInterval(m),m="",a.currentSlide=-1,n(f,k,d,"control"))};this.last=function(){a.running||(clearInterval(m),m="",a.currentSlide=a.totalSlides-2,n(f,k,d,"control"))};this["goto"]=function(b){a.running||(clearInterval(m),m="",q.attr("src",a.currentImage.attr("src")),a.currentSlide=b-1,n(f,k,d,"control"))};this.isRunning=function(){return a.running};this.isStopped=
function(){return a.stop};this.isPaused=function(){return a.paused};this.getSlider=function(){return f};this.getCurrentSlide=function(){return a.currentSlide};this.getTotalSlides=function(){return a.totalSlides};this.destroy=function(){clearInterval(m);m="";f.remove()};d.afterLoad.call(this);return this};b.fn.nivoSlider=function(p){return this.each(function(t,d){var s=b(this);if(s.data("nivoslider"))return s.data("nivoslider");var a=new x(this,p);s.data("nivoslider",a)})};b.fn.nivoSlider.defaults=
{effect:"random",slices:15,boxCols:8,boxRows:4,animSpeed:500,pauseTime:3E3,startSlide:0,directionNav:!0,controlNav:!0,controlNavThumbs:!1,pauseOnHover:!0,manualAdvance:!1,prevText:"Prev",nextText:"Next",randomStart:!1,beforeChange:function(){},afterChange:function(){},slideshowEnd:function(){},lastSlide:function(){},afterLoad:function(){}};b.fn._reverse=[].reverse})(jQuery);
